#############################################################################
# Makefile for building: debug64/imgAnnotation
# Generated by qmake (2.01a) (Qt 4.3.3) on: Thu Jan 17 15:05:48 2008
# Project:  imgAnnotation.pro
# Template: app
# Command: /home/clear/local/bin64/qmake -unix -o Makefile imgAnnotation.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/home/clear/local/usr/qt4/mkspecs/linux-g++-64 -I. -I/home/clear/local/include/qt4/QtCore -I/home/clear/local/include/qt4/QtCore -I/home/clear/local/include/qt4/QtGui -I/home/clear/local/include/qt4/QtGui -I/home/clear/local/include/qt4 -Isrc -I../common/src/annotation -I../common/src -Isrc/tmp -Isrc/ui
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/home/clear/local/arch/x86_64/lib
LIBS          = $(SUBLIBS)  -L/home/clear/local/arch/x86_64/lib -lcv -lcxcore -lQtGui -L/home/clear/local/arch/x86_64/lib -L/usr/X11R6/lib64 -lpng -lSM -lICE -pthread -pthread -lXi -lXrender -lXrandr -lXfixes -lXcursor -lXinerama -lfreetype -lfontconfig -lXext -lX11 -lQtCore -lz -lm -pthread -lgthread-2.0 -lglib-2.0 -lrt -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/clear/local/bin64/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = src/tmp/

####### Files

SOURCES       = src/AnnotationsPixmapWidget.cpp \
		src/functions.cpp \
		src/ImageExtractDialog.cpp \
		src/main.cpp \
		src/MainWindow.cpp \
		src/PixmapWidget.cpp \
		src/ScrollAreaNoWheel.cpp \
		../common/src/annotation/ImgAnnotations.cpp src/tmp/moc_AnnotationsPixmapWidget.cpp \
		src/tmp/moc_ImageExtractDialog.cpp \
		src/tmp/moc_MainWindow.cpp \
		src/tmp/moc_PixmapWidget.cpp \
		src/tmp/moc_ScrollAreaNoWheel.cpp
OBJECTS       = src/tmp/AnnotationsPixmapWidget.o \
		src/tmp/functions.o \
		src/tmp/ImageExtractDialog.o \
		src/tmp/main.o \
		src/tmp/MainWindow.o \
		src/tmp/PixmapWidget.o \
		src/tmp/ScrollAreaNoWheel.o \
		src/tmp/ImgAnnotations.o \
		src/tmp/moc_AnnotationsPixmapWidget.o \
		src/tmp/moc_ImageExtractDialog.o \
		src/tmp/moc_MainWindow.o \
		src/tmp/moc_PixmapWidget.o \
		src/tmp/moc_ScrollAreaNoWheel.o
DIST          = /home/clear/local/usr/qt4/mkspecs/common/g++.conf \
		/home/clear/local/usr/qt4/mkspecs/common/unix.conf \
		/home/clear/local/usr/qt4/mkspecs/common/linux.conf \
		/home/clear/local/usr/qt4/mkspecs/qconfig.pri \
		/home/clear/local/usr/qt4/mkspecs/features/qt_functions.prf \
		/home/clear/local/usr/qt4/mkspecs/features/qt_config.prf \
		/home/clear/local/usr/qt4/mkspecs/features/exclusive_builds.prf \
		/home/clear/local/usr/qt4/mkspecs/features/default_pre.prf \
		/home/clear/local/usr/qt4/mkspecs/features/debug.prf \
		/home/clear/local/usr/qt4/mkspecs/features/default_post.prf \
		/home/clear/local/usr/qt4/mkspecs/features/qt.prf \
		/home/clear/local/usr/qt4/mkspecs/features/unix/thread.prf \
		/home/clear/local/usr/qt4/mkspecs/features/moc.prf \
		/home/clear/local/usr/qt4/mkspecs/features/warn_on.prf \
		/home/clear/local/usr/qt4/mkspecs/features/resources.prf \
		/home/clear/local/usr/qt4/mkspecs/features/uic.prf \
		/home/clear/local/usr/qt4/mkspecs/features/yacc.prf \
		/home/clear/local/usr/qt4/mkspecs/features/lex.prf \
		imgAnnotation.pro
QMAKE_TARGET  = imgAnnotation
DESTDIR       = debug64/
TARGET        = debug64/imgAnnotation

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): src/ui/ui_ImageExtractDialog.h src/ui/ui_MainWindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) debug64/ || $(MKDIR) debug64/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: imgAnnotation.pro  /home/clear/local/usr/qt4/mkspecs/linux-g++-64/qmake.conf /home/clear/local/usr/qt4/mkspecs/common/g++.conf \
		/home/clear/local/usr/qt4/mkspecs/common/unix.conf \
		/home/clear/local/usr/qt4/mkspecs/common/linux.conf \
		/home/clear/local/usr/qt4/mkspecs/qconfig.pri \
		/home/clear/local/usr/qt4/mkspecs/features/qt_functions.prf \
		/home/clear/local/usr/qt4/mkspecs/features/qt_config.prf \
		/home/clear/local/usr/qt4/mkspecs/features/exclusive_builds.prf \
		/home/clear/local/usr/qt4/mkspecs/features/default_pre.prf \
		/home/clear/local/usr/qt4/mkspecs/features/debug.prf \
		/home/clear/local/usr/qt4/mkspecs/features/default_post.prf \
		/home/clear/local/usr/qt4/mkspecs/features/qt.prf \
		/home/clear/local/usr/qt4/mkspecs/features/unix/thread.prf \
		/home/clear/local/usr/qt4/mkspecs/features/moc.prf \
		/home/clear/local/usr/qt4/mkspecs/features/warn_on.prf \
		/home/clear/local/usr/qt4/mkspecs/features/resources.prf \
		/home/clear/local/usr/qt4/mkspecs/features/uic.prf \
		/home/clear/local/usr/qt4/mkspecs/features/yacc.prf \
		/home/clear/local/usr/qt4/mkspecs/features/lex.prf \
		/home/clear/local/arch/x86_64/lib/libQtGui.prl \
		/home/clear/local/arch/x86_64/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile imgAnnotation.pro
/home/clear/local/usr/qt4/mkspecs/common/g++.conf:
/home/clear/local/usr/qt4/mkspecs/common/unix.conf:
/home/clear/local/usr/qt4/mkspecs/common/linux.conf:
/home/clear/local/usr/qt4/mkspecs/qconfig.pri:
/home/clear/local/usr/qt4/mkspecs/features/qt_functions.prf:
/home/clear/local/usr/qt4/mkspecs/features/qt_config.prf:
/home/clear/local/usr/qt4/mkspecs/features/exclusive_builds.prf:
/home/clear/local/usr/qt4/mkspecs/features/default_pre.prf:
/home/clear/local/usr/qt4/mkspecs/features/debug.prf:
/home/clear/local/usr/qt4/mkspecs/features/default_post.prf:
/home/clear/local/usr/qt4/mkspecs/features/qt.prf:
/home/clear/local/usr/qt4/mkspecs/features/unix/thread.prf:
/home/clear/local/usr/qt4/mkspecs/features/moc.prf:
/home/clear/local/usr/qt4/mkspecs/features/warn_on.prf:
/home/clear/local/usr/qt4/mkspecs/features/resources.prf:
/home/clear/local/usr/qt4/mkspecs/features/uic.prf:
/home/clear/local/usr/qt4/mkspecs/features/yacc.prf:
/home/clear/local/usr/qt4/mkspecs/features/lex.prf:
/home/clear/local/arch/x86_64/lib/libQtGui.prl:
/home/clear/local/arch/x86_64/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile imgAnnotation.pro

dist: 
	@$(CHK_DIR_EXISTS) src/tmp/imgAnnotation1.0.0 || $(MKDIR) src/tmp/imgAnnotation1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) src/tmp/imgAnnotation1.0.0/ && $(COPY_FILE) --parents src/AnnotationsPixmapWidget.h src/functions.h src/ImageExtractDialog.h src/MainWindow.h src/PixmapWidget.h src/ScrollAreaNoWheel.h ../common/src/annotation/ImgAnnotations.h src/tmp/imgAnnotation1.0.0/ && $(COPY_FILE) --parents src/AnnotationsPixmapWidget.cpp src/functions.cpp src/ImageExtractDialog.cpp src/main.cpp src/MainWindow.cpp src/PixmapWidget.cpp src/ScrollAreaNoWheel.cpp ../common/src/annotation/ImgAnnotations.cpp src/tmp/imgAnnotation1.0.0/ && $(COPY_FILE) --parents src/ImageExtractDialog.ui src/MainWindow.ui src/tmp/imgAnnotation1.0.0/ && (cd `dirname src/tmp/imgAnnotation1.0.0` && $(TAR) imgAnnotation1.0.0.tar imgAnnotation1.0.0 && $(COMPRESS) imgAnnotation1.0.0.tar) && $(MOVE) `dirname src/tmp/imgAnnotation1.0.0`/imgAnnotation1.0.0.tar.gz . && $(DEL_FILE) -r src/tmp/imgAnnotation1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: src/tmp/moc_AnnotationsPixmapWidget.cpp src/tmp/moc_ImageExtractDialog.cpp src/tmp/moc_MainWindow.cpp src/tmp/moc_PixmapWidget.cpp src/tmp/moc_ScrollAreaNoWheel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) src/tmp/moc_AnnotationsPixmapWidget.cpp src/tmp/moc_ImageExtractDialog.cpp src/tmp/moc_MainWindow.cpp src/tmp/moc_PixmapWidget.cpp src/tmp/moc_ScrollAreaNoWheel.cpp
src/tmp/moc_AnnotationsPixmapWidget.cpp: src/PixmapWidget.h \
		src/AnnotationsPixmapWidget.h
	/home/clear/local/arch/x86_64/bin/moc $(DEFINES) $(INCPATH) src/AnnotationsPixmapWidget.h -o src/tmp/moc_AnnotationsPixmapWidget.cpp

src/tmp/moc_ImageExtractDialog.cpp: src/ui/ui_ImageExtractDialog.h \
		src/MainWindow.h \
		src/ui/ui_MainWindow.h \
		src/ScrollAreaNoWheel.h \
		src/ImageExtractDialog.h
	/home/clear/local/arch/x86_64/bin/moc $(DEFINES) $(INCPATH) src/ImageExtractDialog.h -o src/tmp/moc_ImageExtractDialog.cpp

src/tmp/moc_MainWindow.cpp: src/ui/ui_MainWindow.h \
		src/ScrollAreaNoWheel.h \
		src/MainWindow.h
	/home/clear/local/arch/x86_64/bin/moc $(DEFINES) $(INCPATH) src/MainWindow.h -o src/tmp/moc_MainWindow.cpp

src/tmp/moc_PixmapWidget.cpp: src/PixmapWidget.h
	/home/clear/local/arch/x86_64/bin/moc $(DEFINES) $(INCPATH) src/PixmapWidget.h -o src/tmp/moc_PixmapWidget.cpp

src/tmp/moc_ScrollAreaNoWheel.cpp: src/ScrollAreaNoWheel.h
	/home/clear/local/arch/x86_64/bin/moc $(DEFINES) $(INCPATH) src/ScrollAreaNoWheel.h -o src/tmp/moc_ScrollAreaNoWheel.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: src/ui/ui_ImageExtractDialog.h src/ui/ui_MainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) src/ui/ui_ImageExtractDialog.h src/ui/ui_MainWindow.h
src/ui/ui_ImageExtractDialog.h: src/ImageExtractDialog.ui
	/home/clear/local/arch/x86_64/bin/uic src/ImageExtractDialog.ui -o src/ui/ui_ImageExtractDialog.h

src/ui/ui_MainWindow.h: src/MainWindow.ui
	/home/clear/local/arch/x86_64/bin/uic src/MainWindow.ui -o src/ui/ui_MainWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

src/tmp/AnnotationsPixmapWidget.o: src/AnnotationsPixmapWidget.cpp src/AnnotationsPixmapWidget.h \
		src/PixmapWidget.h \
		src/MainWindow.h \
		src/ui/ui_MainWindow.h \
		src/ScrollAreaNoWheel.h \
		src/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/AnnotationsPixmapWidget.o src/AnnotationsPixmapWidget.cpp

src/tmp/functions.o: src/functions.cpp src/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/functions.o src/functions.cpp

src/tmp/ImageExtractDialog.o: src/ImageExtractDialog.cpp src/ImageExtractDialog.h \
		src/ui/ui_ImageExtractDialog.h \
		src/MainWindow.h \
		src/ui/ui_MainWindow.h \
		src/ScrollAreaNoWheel.h \
		src/PixmapWidget.h \
		src/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/ImageExtractDialog.o src/ImageExtractDialog.cpp

src/tmp/main.o: src/main.cpp src/MainWindow.h \
		src/ui/ui_MainWindow.h \
		src/ScrollAreaNoWheel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/main.o src/main.cpp

src/tmp/MainWindow.o: src/MainWindow.cpp src/MainWindow.h \
		src/ui/ui_MainWindow.h \
		src/ScrollAreaNoWheel.h \
		src/functions.h \
		src/ImageExtractDialog.h \
		src/ui/ui_ImageExtractDialog.h \
		src/AnnotationsPixmapWidget.h \
		src/PixmapWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/MainWindow.o src/MainWindow.cpp

src/tmp/PixmapWidget.o: src/PixmapWidget.cpp src/PixmapWidget.h \
		src/MainWindow.h \
		src/ui/ui_MainWindow.h \
		src/ScrollAreaNoWheel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/PixmapWidget.o src/PixmapWidget.cpp

src/tmp/ScrollAreaNoWheel.o: src/ScrollAreaNoWheel.cpp src/ScrollAreaNoWheel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/ScrollAreaNoWheel.o src/ScrollAreaNoWheel.cpp

src/tmp/ImgAnnotations.o: ../common/src/annotation/ImgAnnotations.cpp ../common/src/annotation/ImgAnnotations.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/ImgAnnotations.o ../common/src/annotation/ImgAnnotations.cpp

src/tmp/moc_AnnotationsPixmapWidget.o: src/tmp/moc_AnnotationsPixmapWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/moc_AnnotationsPixmapWidget.o src/tmp/moc_AnnotationsPixmapWidget.cpp

src/tmp/moc_ImageExtractDialog.o: src/tmp/moc_ImageExtractDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/moc_ImageExtractDialog.o src/tmp/moc_ImageExtractDialog.cpp

src/tmp/moc_MainWindow.o: src/tmp/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/moc_MainWindow.o src/tmp/moc_MainWindow.cpp

src/tmp/moc_PixmapWidget.o: src/tmp/moc_PixmapWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/moc_PixmapWidget.o src/tmp/moc_PixmapWidget.cpp

src/tmp/moc_ScrollAreaNoWheel.o: src/tmp/moc_ScrollAreaNoWheel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/tmp/moc_ScrollAreaNoWheel.o src/tmp/moc_ScrollAreaNoWheel.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

